# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reproduce/proto/pipeline_config.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pipeline_spec_pb2 as pipeline__spec__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%reproduce/proto/pipeline_config.proto\x12\x10reproduce.config\x1a\x13pipeline_spec.proto\"\xdc\x01\n\x10KubeflowV2Config\x12`\n\x18\x63omponent_resource_specs\x18\x01 \x03(\x0b\x32>.reproduce.config.KubeflowV2Config.ComponentResourceSpecsEntry\x1a\x66\n\x1b\x43omponentResourceSpecsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.reproduce.config.ComponentResourceSpec:\x02\x38\x01\"\xda\x01\n\x15\x43omponentResourceSpec\x12\x61\n\tresources\x18\x01 \x01(\x0b\x32I.ml_pipelines.PipelineDeploymentConfig.PipelineContainerSpec.ResourceSpecH\x00\x88\x01\x01\x12P\n\x03\x65nv\x18\x02 \x03(\x0b\x32\x43.ml_pipelines.PipelineDeploymentConfig.PipelineContainerSpec.EnvVarB\x0c\n\n_resourcesb\x06proto3')



_KUBEFLOWV2CONFIG = DESCRIPTOR.message_types_by_name['KubeflowV2Config']
_KUBEFLOWV2CONFIG_COMPONENTRESOURCESPECSENTRY = _KUBEFLOWV2CONFIG.nested_types_by_name['ComponentResourceSpecsEntry']
_COMPONENTRESOURCESPEC = DESCRIPTOR.message_types_by_name['ComponentResourceSpec']
KubeflowV2Config = _reflection.GeneratedProtocolMessageType('KubeflowV2Config', (_message.Message,), {

  'ComponentResourceSpecsEntry' : _reflection.GeneratedProtocolMessageType('ComponentResourceSpecsEntry', (_message.Message,), {
    'DESCRIPTOR' : _KUBEFLOWV2CONFIG_COMPONENTRESOURCESPECSENTRY,
    '__module__' : 'reproduce.proto.pipeline_config_pb2'
    # @@protoc_insertion_point(class_scope:reproduce.config.KubeflowV2Config.ComponentResourceSpecsEntry)
    })
  ,
  'DESCRIPTOR' : _KUBEFLOWV2CONFIG,
  '__module__' : 'reproduce.proto.pipeline_config_pb2'
  # @@protoc_insertion_point(class_scope:reproduce.config.KubeflowV2Config)
  })
_sym_db.RegisterMessage(KubeflowV2Config)
_sym_db.RegisterMessage(KubeflowV2Config.ComponentResourceSpecsEntry)

ComponentResourceSpec = _reflection.GeneratedProtocolMessageType('ComponentResourceSpec', (_message.Message,), {
  'DESCRIPTOR' : _COMPONENTRESOURCESPEC,
  '__module__' : 'reproduce.proto.pipeline_config_pb2'
  # @@protoc_insertion_point(class_scope:reproduce.config.ComponentResourceSpec)
  })
_sym_db.RegisterMessage(ComponentResourceSpec)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KUBEFLOWV2CONFIG_COMPONENTRESOURCESPECSENTRY._options = None
  _KUBEFLOWV2CONFIG_COMPONENTRESOURCESPECSENTRY._serialized_options = b'8\001'
  _KUBEFLOWV2CONFIG._serialized_start=81
  _KUBEFLOWV2CONFIG._serialized_end=301
  _KUBEFLOWV2CONFIG_COMPONENTRESOURCESPECSENTRY._serialized_start=199
  _KUBEFLOWV2CONFIG_COMPONENTRESOURCESPECSENTRY._serialized_end=301
  _COMPONENTRESOURCESPEC._serialized_start=304
  _COMPONENTRESOURCESPEC._serialized_end=522
# @@protoc_insertion_point(module_scope)
